version: "3.9"

services:
  db:
    image: postgres:16
    container_name: mn_db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 3s
      retries: 10
    volumes:
      - pgdata:/var/lib/postgresql/data

  users:
    build:
      context: ./services/users
    container_name: mn_users
    env_file: .env
    environment:
      DATABASE_URL: postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:${POSTGRES_PORT}/${POSTGRES_DB}
      JWT_SECRET: ${JWT_SECRET}
      FLASK_ENV: production
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8001:8000"

  notes:
    build:
      context: ./services/notes
    container_name: mn_notes
    env_file: .env
    environment:
      DATABASE_URL: postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:${POSTGRES_PORT}/${POSTGRES_DB}
      JWT_SECRET: ${JWT_SECRET}
      FLASK_ENV: production
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8002:8000"

volumes:
  pgdata:
