name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  backend:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [users, notes]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install deps
        run: |
          cd services/${{ matrix.service }}
          python -m pip install -r requirements.txt
      - name: Run pytest
        env:
          DATABASE_URL: "sqlite:///:memory:"
          JWT_SECRET: "devsecret"
        run: |
          cd services/${{ matrix.service }}
          pytest -q

  frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: frontend/package-lock.json
      - name: Install deps
        run: |
          cd frontend
          npm ci
      - name: Run vitest
        run: |
          cd frontend
          npm test -- --run
